---
- hosts: all
  user: vagrant
  become: true
  vars_files:
    - vars.yml

  pre_tasks:
    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600

  tasks:
    - name: Install MySQL
      apt: 
        name: 
          - "{{ item }}"
        state: present
      loop:
        - mariadb-server
        - mariadb-client
        - python-mysqldb


    - name: Copy .my.cnf file with root password credentials
      template: 
        src: templates/.my.cnf 
        dest: /root/.my.cnf 
        owner: root 
        mode: 0644

    - name: Copy MySQL Config
      copy:
        src: templates/zzz_otrs.cnf
        dest: /etc/mysql/mariadb.conf.d/zzz_otrs.cnf
        owner: root
        mode: 0644

    - name: Fix mysql Config for remote access.
      copy:
        src: templates/50-server.cnf
        dest: /etc/mysql/mariadb.conf.d/50-server.cnf
        owner: root
        mode: 0644

    - name: Start the MySQL service
      service: 
        name: mysql 
        state: restarted

    - name: Create database user
      community.mysql.mysql_user:
        name: otrs
        password: "{{ mysql_root_password }}"
        priv: '*.*:ALL,GRANT'
        state: present
        host: "{{ item }}"
      loop:
          - 127.0.0.1
          - ::1
          - 192.168.50.4
          - "%"
          - localhost

    - name: Removes all anonymous user accounts
      community.mysql.mysql_user:
        name: ''
        host_all: yes
        state: absent


    - name: Update mysql root password for all root accounts
      mysql_user: 
        name: root 
        host: "{{ item }}" 
        password: "{{ mysql_root_password }}"
        state: present
      loop:
        - 127.0.0.1
        - ::1
        - "%"
        - 192.168.50.4
        - localhost

    - name: Create a new database with name 'otrs'
      community.mysql.mysql_db:
        name: otrs
        state: present

